fintech:
  target: dev

  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST', 'postgres') }}"
      user: "{{ env_var('DBT_POSTGRES_USER', 'fintech') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD', 'fintech') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('DBT_POSTGRES_DB', 'fintech') }}"
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA', 'public') }}"
      threads: 2
