fintech:
  target: dev

  outputs:
    dev:
      type: postgres
      host: postgres
      user: fintech
      password: fintech
      port: 5432
      dbname: fintech
      schema: public
      threads: 2