services:

  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: fintech
      POSTGRES_DB: fintech

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui

    ports:
      - "8080:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

    depends_on:
      - kafka

  producer:
    build:
      context: ./producer

    container_name: producer

    env_file:
      - .env

    depends_on:
      - kafka
    
    restart: unless-stopped

  spark:
    build:
      context: ./spark
      
    container_name: spark

    depends_on:
      - kafka

    volumes:
      - ./spark/data:/opt/spark-data
      - ./spark/app:/opt/spark-apps/app

    environment:
      SPARK_SUBMIT_OPTS: "-Duser.home=/tmp -Divy.home=/tmp/.ivy2.5.2"

    restart: unless-stopped

    command: tail -f /dev/null # testowo przy development, docelowo będzie to spark-submit

  dbt:
    build:
      context: ./dbt
    
    container_name: dbt

    ports:
      - "8081:8081"

    volumes:
      - ./dbt:/dbt

    depends_on:
      - postgres

  airflow-init:
    build:
      context: ./airflow

    container_name: airflow-init

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock

    command: airflow db migrate

  airflow:
    build:
      context: ./airflow

    container_name: airflow

    ports:
      - "8088:8080"

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./dbt:/dbt
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - airflow-init
      - postgres

    command: airflow standalone

volumes:
  postgres_data: